### ISSUE TITLE
Selected Tab background color not displayed correctly in Internet Explorer

### ISSUE THREAD

**Issue by Aschmersal** [oohoo/moodle-format_tabtopics#2]
Tried to change the background color for the "selected tab" according to the README file. 

This works fine for Opera, Google chrome, Firefox. For some reasons the color doesnt change in Internet explorer. It still has a color like #2647a0. 

Ist that a known bug? Are there any fixes? 

IE version is 9.0.8112.1642.1
Installed plugin version is Release 2.4.3 (Build: 2013021200)
Moodle version is 2.4.1 (Build: 20130114)

Thanks for any help.

**Comment by bretin** [comment]
Hi,

I didn't notice this bug! 
For information it working on IE 10!

So apparently IE9 doesn't use well background image and background color. 
In order to change the color you have 2 solutions:
1. Instead of typing `background-color: #cb2121 !important;` type `background: #cb2121 !important;`. This solution will remove the image of the gradient.
2. If you want to keep the gradient you will have to copy the gradient.png into your theme and you will be able to redefine the whole background like `background:  #cb2121 url([[pix:theme|gradient]]) repeat-x;`

Hope this will works for you!

Nicolas

**Comment by Aschmersal** [comment]
Hi Nicolas, 

thanks for the tip. It works fine now even for IE9. 

The tabtopics is a nice plugin by the way. Good job :-)

Cheers
Andreas
